name: ToggleOn
favicon: null
layout_spectrum: 0.25475
typography_spectrum: 0.74923
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ToggleOn brings new technologies to market
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#66110e'
    - '#d04a3e'
    - '#6f6f6f'
    - '#a2a2a2'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
